#! /bin/sh
#
# randCol.sh
# Copyright (C) 2018 g <g@ABCL>
#
# Distributed under terms of the MIT license.
#

while read -r line || [[ -n "$line" ]]; do
    echo -e "\e[3$(( $RANDOM * 15 / 32767 + 1 ))m$line"
done
